development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sample_app_development
  username: <%= ENV["USER"] %>
  password:
  allow_concurrency: true
  pool: 5
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sample_app_test
  username: <%= ENV["USER"] %>
  password:
  allow_concurrency: true
  pool: 5
  min_messages: error
