development:
  adapter: postgresql
  encoding: unicode
  template: template0
  host: localhost
  database: sample_app_development
  username: <%= ENV["USER"] %>
  password:
  allow_concurrency: true
  pool: 5
  min_messages: warning

test: &test
  adapter: postgresql
  encoding: unicode
  template: template0
  host: localhost
  database: sample_app_test
  username: <%= ENV["USER"] %>
  password:
  allow_concurrency: true
  pool: 5
  min_messages: error

cucumber:
  <<: *test